.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH GAMBATTE_QT 6 "august 27, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
gambatte_qt \- emulate Nintendo's Game Boy (Color) handheld device
.SH SYNOPSIS
.B gambatte_qt
.RI [ romfile ]
.SH DESCRIPTION
.B gambatte_qt
opens a Game Boy (Color) emulator GUI, and optionally loads a
.I romfile
as Game Boy cartridge on start up.
.SH AUTHOR
Gambatte and this manual page was written by Sindre Aamås <aamas@stud.ntnu.no>.
