global_cflags = ARGUMENTS.get('CFLAGS', '-Wall -Wextra -O2 -g')
global_cxxflags = ARGUMENTS.get('CXXFLAGS', global_cflags + ' -fno-exceptions -fno-rtti')
global_defines = ' -DHAVE_STDINT_H'

env = Environment(CPPPATH = ['.', '../libgambatte/include'],
                  CFLAGS = global_cflags + global_defines,
                  CXXFLAGS = global_cxxflags + global_defines)

sourceFiles = Split('''
			testrunner.cpp
			../libgambatte/libgambatte.a
		   ''')

conf = env.Configure()
conf.CheckLib('z')
conf.CheckLib('png')
conf.Finish()

env.Program('testrunner', sourceFiles)
