global_cflags = ARGUMENTS.get('CFLAGS', '-Wall -Wextra -O2 -g')
global_cxxflags = ARGUMENTS.get('CXXFLAGS', global_cflags + ' -fno-exceptions -fno-rtti')
global_defines = ' -DHAVE_STDINT_H'
vars = Variables()
vars.Add('CC')
vars.Add('CXX')

env = Environment(CPPPATH = ['.', '../common', '../libgambatte/include'],
                  CFLAGS = global_cflags + global_defines,
                  CXXFLAGS = global_cxxflags + global_defines,
                  LIBS = 'm',
                  variables = vars)

sourceFiles = Split('''
			testrunner.cpp
			../libgambatte/libgambatte.a
		   ''')

conf = env.Configure()
conf.CheckLib('z')
conf.CheckLib('png')
conf.Finish()

env.Program('testrunner', sourceFiles)
