global_cflags = ARGUMENTS.get('CFLAGS', '-Wall -Wextra -O2 -fomit-frame-pointer')
global_cxxflags = ARGUMENTS.get('CXXFLAGS', global_cflags + ' -fno-exceptions -fno-rtti')
global_defines = ' -DHAVE_STDINT_H'

env = Environment(CPPPATH = ['src', '../libgambatte/include'],
                  LIBS = ['gambatte'],
                  LIBPATH = '../libgambatte',
                  CFLAGS = global_cflags + global_defines,
                  CXXFLAGS = global_cxxflags + global_defines)

env.ParseConfig('sdl-config --cflags --libs')

sourceFiles = Split('''
			src/gambatte_sdl.cpp
			src/parser.cpp
			src/sdlblitter.cpp
			src/str_to_sdlkey.cpp
			src/syncfunc.cpp
		   ''')

conf = env.Configure()

if conf.CheckLib('z'):
	env.Append(LIBS = ['z'])

conf.Finish()

env.Program('gambatte_sdl', sourceFiles)
