env = Environment(CPPPATH = ['.', '../libgambatte/include'],
                  LIBS = ['gambatte'],
                  LIBPATH = '../libgambatte',
                  CPPFLAGS = ARGUMENTS.get('CPPFLAGS', '-Wall -O2 -fno-exceptions -fno-rtti -fomit-frame-pointer'))

env.ParseConfig('sdl-config --cflags --libs')

sourceFiles = Split('''
			gambatte_sdl.cpp
		   ''')

env.Program(sourceFiles)
